# Generated by Django 5.2 on 2026-06-22 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('gcse', 'GCSE'), ('a_level', 'A-Level'), ('undergraduate',
                 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('other', 'Other')], max_length=20)),
                ('exam_board', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='courses', to='courses.subject')),
            ],
            options={
                'ordering': ['subject__name', 'name'],
                'unique_together': {('subject', 'name', 'level')},
            },
        ),
    ]
